import { useState } from 'react'
import { ArrowRight, BadgeCheck, Bolt, Check, Clock3, House, Link, Mail, MapPin, Menu, Phone, ShieldCheck, Sparkles, X } from 'lucide-react'
import './App.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [formSent, setFormSent] = useState(false)
  const closeMenu = () => setMenuOpen(false)

  return (
    <div className="site-shell">
      <div className="topline"><div className="container topbar-content"><span><MapPin size={14} /> Wrocław i okolice</span><span className="topbar-note">Dojeżdżamy tam, gdzie inni nie chcą</span><a href="tel:+48501608421"><Phone size={14} /> +48 501 608 421</a></div></div>
      <header className="navbar container"><a className="brand" href="#start" onClick={closeMenu}><span className="brand-mark"><Bolt size={21} fill="currentColor" /></span><span>Tani<span className="brand-accent">Elektryk</span><small>WROCŁAW / 24H</small></span></a><button className="menu-toggle" type="button" aria-label="Otwórz menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={24} /> : <Menu size={24} />}</button><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}><a href="#uslugi" onClick={closeMenu}>Usługi</a><a href="#dlaczego-my" onClick={closeMenu}>Dlaczego my</a><a href="#proces" onClick={closeMenu}>Jak działamy</a><a href="#kontakt" onClick={closeMenu}>Kontakt</a><a className="nav-call" href="tel:+48501608421"><Phone size={16} /> Zadzwoń teraz</a></nav></header>
      <main>
        <section className="hero container" id="start"><div className="hero-copy reveal"><h1>Usługi elektryka<br /><em>nie muszą być drogie.</em></h1><p className="hero-lead">Szybkie i uczciwe usługi elektryczne dla mieszkań, domów i firm we Wrocławiu.</p><div className="hero-actions"><a className="button button-primary" href="#kontakt">Umów wizytę <ArrowRight size={18} /></a><a className="text-link" href="tel:+48501608421"><Phone size={17} /> 501 608 421</a></div><div className="hero-trust"><span><BadgeCheck size={17} /> Uprawnienia SEP</span><span><Clock3 size={17} /> Termin nawet dziś</span></div></div><div className="hero-visual reveal reveal-delay"><div className="image-frame"><img src="https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=85" alt="Elektryk podczas pracy przy instalacji" /><div className="image-label"><span className="label-icon"><ShieldCheck size={20} /></span><span><strong>Bezpiecznie</strong><small>od pierwszego pomiaru</small></span></div></div><div className="hero-sticker"><Sparkles size={16} /><strong>4.9</strong><span>/ 5</span><small>opinie klientów</small></div></div></section>
        <div className="marquee"><div className="marquee-track"><span>INSTALACJE</span><i /><span>AWARIE</span><i /><span>POMIARY</span><i /><span>OŚWIETLENIE</span><i /><span>MODERNIZACJE</span><i /><span>INSTALACJE</span><i /><span>AWARIE</span><i /></div></div>
        <section className="section services container" id="uslugi"><div className="section-heading"><div><p className="kicker">Co możemy zrobić</p><h2>Usługi bez<br /><span>zbędnego gadania.</span></h2></div><p className="section-intro">Od małej usterki po kompletną instalację. Zawsze jasno mówimy, co robimy i ile to kosztuje.</p></div><div className="service-grid"><article className="service-card service-featured"><span className="card-number">01</span><div className="service-icon"><House size={25} /></div><h3>Instalacje elektryczne</h3><p>Nowe instalacje w domach, mieszkaniach i lokalach. Od projektu po ostatnie gniazdko.</p><a href="#kontakt">Dowiedz się więcej <ArrowRight size={16} /></a></article><article className="service-card"><span className="card-number">02</span><div className="service-icon"><Bolt size={25} /></div><h3>Awarie i naprawy</h3><p>Brak prądu, zwarcie, migające światło? Znajdziemy przyczynę i usuniemy problem.</p><a href="#kontakt">Dowiedz się więcej <ArrowRight size={16} /></a></article><article className="service-card"><span className="card-number">03</span><div className="service-icon"><ShieldCheck size={25} /></div><h3>Pomiary i odbiory</h3><p>Profesjonalne pomiary instalacji i protokoły potrzebne do odbioru nieruchomości.</p><a href="#kontakt">Dowiedz się więcej <ArrowRight size={16} /></a></article></div></section>
        <section className="why-section" id="dlaczego-my"><div className="container why-layout"><div className="why-photo"><img src="https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=1000&q=85" alt="Narzędzia elektryka" /><span className="photo-note">Dobra robota<br /><strong>zostaje na lata.</strong></span></div><div className="why-copy"><p className="kicker">Po prostu dobrze</p><h2>Nie kombinujemy.<br /><span>Robimy porządnie.</span></h2><p className="why-lead">Wybierasz fachowca, nie loterię. Pracujemy czysto, terminowo i z szacunkiem do Twojego domu.</p><ul className="check-list"><li><span><Check size={15} /></span><div><strong>Wycena przed pracą</strong><small>Wiesz, na czym stoisz. Bez niespodzianek.</small></div></li><li><span><Check size={15} /></span><div><strong>Gwarancja na usługę</strong><small>Bierzemy odpowiedzialność za swoją pracę.</small></div></li><li><span><Check size={15} /></span><div><strong>Porządek po robocie</strong><small>Zostawiamy miejsce w lepszym stanie niż zastaliśmy.</small></div></li></ul></div></div></section>
        <section className="process section container" id="proces"><div className="section-heading process-heading"><div><p className="kicker">Bez stresu</p><h2>Trzy kroki do<br /><span>sprawnego prądu.</span></h2></div><p className="section-intro">Zadzwoń lub napisz. Resztą zajmiemy się my.</p></div><div className="process-grid"><div className="process-step"><span>01</span><h3>Opowiedz, co się dzieje</h3><p>Krótko opisujesz problem albo planowaną pracę. Możesz wysłać zdjęcie.</p></div><div className="process-step"><span>02</span><h3>Ustalamy konkrety</h3><p>Podajemy dostępny termin i uczciwą wycenę przed rozpoczęciem prac.</p></div><div className="process-step"><span>03</span><h3>Robimy swoje</h3><p>Przyjeżdżamy na czas, działamy sprawnie i zostawiamy po sobie porządek.</p></div></div></section>
        <section className="contact-section" id="kontakt"><div className="container contact-layout"><div className="contact-copy"><p className="kicker">Masz temat?</p><h2>Porozmawiajmy o<br /><span>Twojej instalacji.</span></h2><p>Napisz kilka słów albo zadzwoń. Odpowiemy tak szybko, jak to możliwe.</p><div className="contact-details"><a href="tel:+48501608421"><span><Phone size={19} /></span><div><small>Telefon</small><strong>+48 501 608 421</strong></div></a><a href="mailto:kontakt@tanielektryk.pl"><span><Mail size={19} /></span><div><small>E-mail</small><strong>kontakt@tanielektryk.pl</strong></div></a></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setFormSent(true) }}>{formSent ? <div className="form-success"><span><Check size={25} /></span><h3>Wiadomość wysłana.</h3><p>Odezwiemy się do Ciebie najszybciej, jak się da.</p><button type="button" className="text-link" onClick={() => setFormSent(false)}>Wyślij kolejną wiadomość</button></div> : <><div className="form-row"><label>Imię<input type="text" placeholder="Jak masz na imię?" required /></label><label>Telefon<input type="tel" placeholder="Twój numer" required /></label></div><label>E-mail<input type="email" placeholder="Twój adres e-mail" required /></label><label>W czym możemy pomóc?<textarea placeholder="Napisz kilka słów o zleceniu..." rows="4" required /></label><button className="button button-dark" type="submit">Wyślij zapytanie <ArrowRight size={18} /></button></>}</form></div></section>
      </main>
      <footer className="footer"><div className="container footer-content"><a className="brand" href="#start"><span className="brand-mark"><Bolt size={21} fill="currentColor" /></span><span>Tani<span className="brand-accent">Elektryk</span><small>WROCŁAW / 24H</small></span></a><p>Sprawny prąd. Spokojna głowa.</p><div className="footer-links"><a href="https://instagram.com" aria-label="Profil społecznościowy"><Link size={18} /></a><a href="mailto:kontakt@tanielektryk.pl" aria-label="E-mail"><Mail size={18} /></a></div></div><div className="container footer-bottom"><span>© 2024 Tani Elektryk</span><span>Wrocław i okolice</span></div></footer>
    </div>
  )
}

export default App
